### ISSUE TITLE
p12473 - HGT debits more assets than specified in _amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#109]
p12473

medium

# HGT debits more assets than specified in _amount

## Summary

When calling `HGT.withdraw()`, the `_debitFrom` function debits an extra wei unnecessarily

## Vulnerability Detail

In the `_debitFrom` function, the `amount` is manually rounded down. This is unnecessary (confirmed w/ sponsor) as

1. solidity automatically rounds down
2. if it’s a clean division i.e. numerator % divisor = 0

Moreover, because of the requirement that amount > 1, a user can never withdraw exactly 1 token.

## Impact

User receives `amount-1` wei of tokens. This off by 1 error can potentially be disastrous depending on how the receiving contract handles it and the imbalance can build up over time.

## Code Snippet

https://github.com/hubble-exchange/hubble-protocol/blob/d89714101dd3494b132a3e3f9fed9aca4e19aef6/contracts/HGT.sol#L24-L30

## Tool used

Manual Review

## Recommendation
Remove the logic that rounds down
```solidity
function _debitFrom(address, uint _amount) internal virtual override returns(uint) {
    circulatingSupply -= _amount;
    _amount = _amount / SCALING_FACTOR;
    return _amount;
}
```

**Comment by P12473** [comment]
Escalate

I've spoken to the sponsor about this and confirmed it is an issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I've spoken to the sponsor about this and confirmed it is an issue. While the loss of funds is negligible, it is still an off-by-1 accounting error that can be an issue for integrating contracts.

    You've deleted an escalation for this issue.
