### ISSUE TITLE
p12473 - Frontrunning buyCollateralFromAuction prevents other non bot users from participating

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#110]
p12473

medium

# Frontrunning buyCollateralFromAuction prevents other non bot users from participating

## Summary

`buyCollateralFromAuction` can be frontrunned by a bot. This is an almost risk free arbitrage (depending on secondary market liquidity) for the bot and prevents other legitimate users from purchasing these assets.

## Vulnerability Detail

Game theory states that everyone will wait until the very end to buy the assets since it provides the largest discount but most likely someone will attempt to buy a little earlier. Once someone starts buying, everyone else will start buying as well. If a MEV bot sees this, the bot can frontrun and purchase all the assets. If nobody buys it then the bot will buy it at the very last second to get the biggest discount.

Non bot users will never be able to compete with a bot in this FCFS auction.

## Impact

Other legitimate but non bot users will not be able to purchase any assets.

## Code Snippet

https://github.com/hubble-exchange/hubble-protocol/blob/d89714101dd3494b132a3e3f9fed9aca4e19aef6/contracts/InsuranceFund.sol#L184-L199

## Tool used

Manual Review

## Recommendation

Use a commit reveal scheme for the auction.

- For example, during the first 2 hours, users can commit a hash e.g. keccak256(auction nonce, price, qty, buyer, salt).
- In the second phase (perhaps another 2 hours) is for users to reveal their hash. Some state variables are used to keep a running record of all revealed prices and quantities that users are willing to purchase.
    - This logic needs to also ensure that the total amount of assets that can be bought by the top X payers cannot exceed the amount of assets to be sold and that any other user that doesn’t fall in this group of top buyers cannot purchase any assets.
- Once the commit phase is over, users in this top paying group can complete their payment to buy the collateral.

Note: do not push the assets to the users but rather have them pull it instead.

**Comment by P12473** [comment]
escalate

With the prevalence of MEV and frontrunning bots, I would argue that an auction being able to be completed by only 1 bot is almost equivalent to the [DOS because highest bidder reverts on refund vulnerability](https://consensys.github.io/smart-contract-best-practices/attacks/denial-of-service/#:~:text=DoS%20with%20(Unexpected)%20revert,-Consider%20a%20simple&text=When%20it%20tries%20to%20refund,their%20address%20will%20always%20fail.). The sponsor should use a different auction scheme to mitigation this entirely.

**Comment by sherlock-admin2** [comment]
> escalate
> 
> While the auction is working as intended, the prevalence of MEV and frontrunning bots makes the auction monopolized entirely by bots. From a protocol's pov, it doesn't matter who completes the auction as long as someone buys it however from an end user's pov, the auctions being dominated by bots is a bad experience and is effectively a DOS for legitimate non bot users.
> 
> The sponsor should consider using a different auction scheme to mitigation this entirely.

    You've deleted an escalation for this issue.

**Comment by ctf-sec** [comment]
Don't see a issue here 

> buyCollateralFromAuction can be frontrunned by a bot. This is an almost risk free arbitrage (depending on secondary market liquidity) for the bot and prevents other legitimate users from purchasing these assets.

as long as there are buyer to finish the end, code working as intended

+ 

no matter how to fix the issue, there are bot that can frontrun user and win auction, bot are faster than user when snipering transaction anyway.

**Comment by ghost** [comment]
> Don't see a issue here
> 
> > buyCollateralFromAuction can be frontrunned by a bot. This is an almost risk free arbitrage (depending on secondary market liquidity) for the bot and prevents other legitimate users from purchasing these assets.
> 
> as long as there are buyer to finish the end, code working as intended
> 
> 
> no matter how to fix the issue, there are bot that can frontrun user and win auction, bot are faster than user when snipering transaction anyway.

I understand your perspective. I will delete the escalation but would still recommend to the sponsor to rethink how they would auction the assets.
