### ISSUE TITLE
Delvir0 - Possible to drain all vusd from InsureanceFund if user is the only staker

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#172]
Delvir0

medium

# Possible to drain all vusd from InsureanceFund if user is the only staker

## Summary
Due to the calculation of withdrawal, it's possible to drain the contract from vusd if any are stored
## Vulnerability Detail
It's the classic case where someone deposits x amount, withdraws all except 1 wei which leverages the pool (LP) and then drains the pool.

Assume user deposits x amount, requests withdrawal and block.timestamp = unbondTime.
`_withdrawFor` will calculate the amount of vusd to withdraw by:
https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/main/hubble-protocol/contracts/InsuranceFund.sol#L215
When we withdraw x -1 amount and the user is the only one currently invested in the fund, we end up with totalSupply and shares of 1.
Calculation of amount to withdraw will be `(vusdBalance * 1) / 1` = vusdBalance.
Meaning whatever amount of vusd is in the pool, that amount will be withdrawn
## Impact
whatever amount of vusd is in the pool can be withdrawn
## Code Snippet
https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/main/hubble-protocol/contracts/InsuranceFund.sol#L205avd
## Tool used

Manual Review

## Recommendation
Do note that this assumes the following: user deposited and awaited unbonTime to withdraw amount - 1 while no one else has deposited (e.g. without the user ts would be 0).

This would simply be avoided by initial minting an x amount 

Duplicate of #140

**Comment by ctf-sec** [comment]
Escalate

this is a duplicate of #140

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> this is a duplicate of #140 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #140

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ctf-sec](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/172/#issuecomment-1643684199): accepted
