### ISSUE TITLE
ni8mare - More checks needed for Chainlink price feed return values

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#184]
ni8mare

medium

# More checks needed for Chainlink price feed return values

## Summary
Get `getUnderlyingPrice` in `Oracle.sol` does not check for the return values returned by the Chainlink price feed's `latestRoundData` function.

## Vulnerability Detail
As the summary above states, not checking these values could result in stale/incorrect prices. For example, suppose there is a problem with Chainlink starting a new [round](https://solodit.xyz/issues/5699) and finding consensus on the new value for the oracle. In that case, consumers of this contract may continue using outdated stale data. Another issue that can arise due to insufficient checks on the price of the asset - https://solodit.xyz/issues/6663

## Impact
Stale/Incorrect data will be used for the token prices.

## Code Snippet
https://github.com/hubble-exchange/hubble-protocol/blob/d89714101dd3494b132a3e3f9fed9aca4e19aef6/contracts/Oracle.sol#L24

## Tool used

Manual Review

## Recommendation

It is recommended to use the following checks:

```solidity
require(price > 0, "Negative Oracle Price");
require(block.timestamp - updatedAt <= outdated , "ChainLinkOracle: outdated.");
require(price < maxPrice, "Upper price bound breached");
require(price > minPrice, "Lower price bound breached");
require(answeredInRound >= roundID, "round not complete");
```

Duplicate of #241

**Comment by NishithPat** [comment]
Escalate
This is a duplicate of the issue: https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/241

I mention the Solodit issue -  https://solodit.xyz/issues/6663, which talks about the LUNA issue, due to no underlying check between minPrice and the current price. If you see a 404 error on trying to open the issue, then consider this screenshot:

<img width="1202" alt="Screenshot 2023-07-20 at 7 19 20 AM" src="https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/assets/51897810/fa149299-bb2e-4d65-a2aa-a98661a8632d">

Check the URL in the screenshot, it's for issue 6663.

Also, I recommend taking care of the following checks in my recommendation, which also suggest that this is a duplicate of
https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/241

```solidity
require(price < maxPrice, "Upper price bound breached");
require(price > minPrice, "Lower price bound breached");
```

**Comment by sherlock-admin2** [comment]
> Escalate
> This is a duplicate of the issue: https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/241
> 
> I mention the Solodit issue -  https://solodit.xyz/issues/6663, which talks about the LUNA issue, due to no underlying check between minPrice and the current price. If you see a 404 error on trying to open the issue, then consider this screenshot:
> 
> <img width="1202" alt="Screenshot 2023-07-20 at 7 19 20 AM" src="https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/assets/51897810/fa149299-bb2e-4d65-a2aa-a98661a8632d">
> 
> Check the URL in the screenshot, it's for issue 6663.
> 
> Also, I recommend taking care of the following checks in my recommendation, which also suggest that this is a duplicate of
> https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/241
> 
> ```solidity
> require(price < maxPrice, "Upper price bound breached");
> require(price > minPrice, "Lower price bound breached");
> ```
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Agree with escalation, recommend putting text info the report and not link in the report, not everyone can open solodit

**Comment by Nabeel-javed** [comment]
Escalate for 10 USDC

This should be duplicate of #18

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> This should be duplicate of #18 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by yixxas** [comment]
Escalate

Seems to be a dupe of both #18 and #241 (partial). Judge can decide on this but this issue should at least be rewarded.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Seems to be a dupe of both #18 and #241 (partial). Judge can decide on this but this issue should at least be rewarded.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Nabeel-javed** [comment]
> Escalate
> 
> Seems to be a dupe of both #18 and #241 (partial). Judge can decide on this but this issue should at least be rewarded.

Agree on that

**Comment by NishithPat** [comment]
I do agree that I should have made 2 different issues. But, I have justified why this is a valid duplicate of https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/241 in my escalation and the lead judge also agrees with it.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #241 
Agree that this issue can be considered a duplicate of both issues considering the issue a duplicate of #241 

Note to the Watson: Please describe the exact issue atleast briefly instead of linking external reports.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [NishithPat](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/184/#issuecomment-1643009614): accepted
- [Nabeel-javaid](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/184/#issuecomment-1643798037): accepted
- [yixxas](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/184/#issuecomment-1644348447): accepted
