### ISSUE TITLE
yixxas - Reducing position size can also put the trader below the required margin due to fees paid

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#201]
yixxas

high

# Reducing position size can also put the trader below the required margin due to fees paid

## Summary
`assertMarginRequirement` of a trader is only checked after opening position if position size is increased, i.e. `varGroup.isPositionIncreased`. However, we should also be checking even when position size is reduced due to the fees that is paid.

## Vulnerability Detail
Fee is charged whenever a position is opened. For example, if the mode is maker, then the trader has to pay the maker fee. This means that it is possible for a trader to call `openPosition` with the intention of reducing the size of his position, his position can enter the insufficient margin state at the end of the call. 

```solidity
  function _openPosition(IOrderBook.Order memory order, int256 fillAmount, uint256 fulfillPrice, IOrderBook.OrderExecutionMode mode, bool is2ndTrade) internal returns(uint openInterest) {
        updatePositions(order.trader); // settle funding payments
        uint quoteAsset = abs(fillAmount).toUint256() * fulfillPrice / 1e18;
        int size;
        uint openNotional;
        VarGroup memory varGroup;
        (
            varGroup.realizedPnl,
            varGroup.isPositionIncreased,
            size,
            openNotional,
            openInterest
        ) = amms[order.ammIndex].openPosition(order, fillAmount, fulfillPrice, is2ndTrade);

        {
            int toFeeSink;
            (toFeeSink, varGroup.feeCharged) = _chargeFeeAndRealizePnL(order.trader, varGroup.realizedPnl, quoteAsset, mode);
            if (toFeeSink != 0) {
                marginAccount.transferOutVusd(feeSink, toFeeSink.toUint256());
            }
        }
        {
            // isPositionIncreased is true when the position is increased or reversed
            if (varGroup.isPositionIncreased) {
                assertMarginRequirement(order.trader);
                require(order.reduceOnly == false, "CH: reduceOnly order can only reduce position");
            }
            emit PositionModified(order.trader, order.ammIndex, fillAmount, fulfillPrice, varGroup.realizedPnl, size, openNotional, varGroup.feeCharged, mode, _blockTimestamp());
        }
    }
```

## Impact
Trader can fall below the margin requirement after reducing his position size.

## Code Snippet
https://github.com/hubble-exchange/hubble-protocol/blob/3a6b576eeedc323c70feb3808c665228e5f9b8a5/contracts/ClearingHouse.sol#L140-L169

## Tool used

Manual Review

## Recommendation
`assertMarginRequirement(order.trader)` should be moved out of the `if (varGroup.isPositionIncreased)` scope to ensure that trader has the required margin after reducing position size.

**Comment by 0xvj** [comment]
Escalate

**Comment by sherlock-admin2** [comment]
> Escalate 

    You've deleted an escalation for this issue.

**Comment by IAm0x52** [comment]
Escalate

This should be invalid. The fee charged is always less than the amount being closed. While it is possible for the trader to be under the required margin after reducing their position, their position will guaranteed be more collateralized after closing than before closing. That is to say that a healthy position that reduces their position is never at risk of becoming unhealthy after reducing their position.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should be invalid. The fee charged is always less than the amount being closed. While it is possible for the trader to be under the required margin after reducing their position, their position will guaranteed be more collateralized after closing than before closing. That is to say that a healthy position that reduces their position is never at risk of becoming unhealthy after reducing their position.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by yixxas** [comment]
The issue here is not that reducing a healthy position can put it at risk of liquidation. The issue here is that a user that wants to reduce its position to meet the margin requirements can still be at risk due to the additional fees paid.

There are no reasons to allow users to reduce position, pay fees AND still be at risk. Post reduction should always ensure that user is safe from liquidation.

**Comment by IAm0x52** [comment]
I agree it's bad UX for this to occur but the situation being described is just input validation which isn't a valid issue

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Escalation, this can be considered user input validation with bad UX. 
Don't see this issue as medium.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/201/#issuecomment-1645016241): accepted
