### ISSUE TITLE
yixxas - Incorrect spread validation when `spreadLimit >= 1e6`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#202]
yixxas

medium

# Incorrect spread validation when `spreadLimit >= 1e6`

## Summary
Spread is overvalidated when `spreadLimit >= 1e6`, preventing orders that should be filled to be unable to fill.

## Vulnerability Detail
Based on the inline documentation, having `spreadLimit` set to 1e6 means that 100% variation is allowed, meaning that the protocol should not be preventing any kind of orders from being filled due to too high a spread in price.

> "if spreadLimit >= 1e6 it means that 100% variation is allowed which means shorts at $0 will also pass."

A special case is handled for when `spreadLimit` is set to 1e6 for the lower bound. If `spreadLimit == 1e6`, then even a short price of $0 will be filled. This is clearly intended by the protocol. However, for the upper bound, it continues to limit price to the bound of `oraclePrice * (1e6 + spreadLimit) / 1e6`. This means that even in a supposed allowed "100% variation", if filled price fluctuates outside of more than 2x the oracle price, it forces a revert, but this should not be the case due to the rules set by `spreadLimit`.

## Impact
Spread is overvalidated which prevents orders that are supposed to go through from going through due to upper bound check.

## Code Snippet
https://github.com/hubble-exchange/hubble-protocol/blob/3a6b576eeedc323c70feb3808c665228e5f9b8a5/contracts/orderbooks/OrderBook.sol#L311-L324

## Tool used

Manual Review

## Recommendation
In the case where `spreadLimit >= 1e6`, we should free up the upper limit and allow trades of all prices to go through just like the lower bound.

**Comment by yixxas** [comment]
Escalate

It is clear from the implementation that the protocol is intended and prepared to handle the case where `spreadLimit >= 1e6` as mentioned in this issue. This value can be set by the governance either by `maxLiquidationPriceSpread` or `maxOracleSpreadRatio`. 

Now if we agree that the above premise is true, then there exist a faulty implementation here which prevents the protocol from functioning as intended as this means that users who makes an effective "market order" can be **wrongly** reverted due to the incorrect check. In a highly volatile crypto market, it is not uncommon for tokens/trades/perpetuals to fluctuate more than 2x the current price. A very recent example is XRP, a top 4 coin by market cap that went up almost double on news of lawsuit judgement results against the SEC.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> It is clear from the implementation that the protocol is intended and prepared to handle the case where `spreadLimit >= 1e6` as mentioned in this issue. This value can be set by the governance either by `maxLiquidationPriceSpread` or `maxOracleSpreadRatio`. 
> 
> Now if we agree that the above premise is true, then there exist a faulty implementation here which prevents the protocol from functioning as intended as this means that users who makes an effective "market order" can be **wrongly** reverted due to the incorrect check. In a highly volatile crypto market, it is not uncommon for tokens/trades/perpetuals to fluctuate more than 2x the current price. A very recent example is XRP, a top 4 coin by market cap that went up almost double on news of lawsuit judgement results against the SEC. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xshinobii** [comment]
spread limit can be set more than `1e6`. So if we want to allow price variation up to 200%, we will set `spreadLimit = 2e6`. As can be seen in the below lines, it will not revert. However, in the case of price decreament, it cannot go below 100%, hence lower bound spread is not checked for `spreadLimit >= 1e6`
```
uint bound = oraclePrice * (1e6 + spreadLimit) / 1e6;
require(price <= bound, "AMM.price_GT_bound");

**Comment by hrishibhat** [comment]
@yixxas Do you have any further comments?

**Comment by yixxas** [comment]
Nope, understood sponsor’s perspective.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on Sponsor comments.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yixxas](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/202/#issuecomment-1644363832): rejected
