### ISSUE TITLE
Bauchibred - An outrageously different price could be used in the case where all of the last hour data is negative in `getRoundData()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#244]
Bauchibred

medium

# An outrageously different price could be used in the case where all of the last hour data is negative in `getRoundData()`

## Summary

This check is included in the [getLatestRoundData()](https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/1f9a5ed0ca8f6004bbb7b099ecbb8ae796557849/hubble-protocol/contracts/Oracle.sol#L106-L141) function:

```solidity
  function getLatestRoundData(AggregatorV3Interface _aggregator)
...
        if (latestPrice <= 0) {
            requireEnoughHistory(round);
            (round, finalPrice, latestTimestamp) = getRoundData(_aggregator, round - 1);
        }
...
}
```

Key to note that this function is used for the twap calculation of last hour, problem is that if all of last hour data is negative then the `last positive price` is used, this is obviously an issue as if all instance for the twap price of the last hour is `-ve,` a revert should instead be the best case, than potentially valuing the token at a very outrageous price, since it got worthless already

## Vulnerability Detail

See summary, take a look at the [getLatestRoundData()](https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/1f9a5ed0ca8f6004bbb7b099ecbb8ae796557849/hubble-protocol/contracts/Oracle.sol#L106-L141) function

```solidity


    function getLatestRoundData(AggregatorV3Interface _aggregator)
        internal
        view
        returns (
            uint80,
            uint256 finalPrice,
            uint256
        )
    {
        (uint80 round, int256 latestPrice, , uint256 latestTimestamp, ) = _aggregator.latestRoundData();
        finalPrice = uint256(latestPrice);
        if (latestPrice <= 0) {
            requireEnoughHistory(round);
            (round, finalPrice, latestTimestamp) = getRoundData(_aggregator, round - 1);
        }
        return (round, finalPrice, latestTimestamp);
    }


    function getRoundData(AggregatorV3Interface _aggregator, uint80 _round)
        internal
        view
        returns (
            uint80,
            uint256,
            uint256
        )
    {
        (uint80 round, int256 latestPrice, , uint256 latestTimestamp, ) = _aggregator.getRoundData(_round);
        while (latestPrice <= 0) {
            requireEnoughHistory(round);
            round = round - 1;
            (, latestPrice, , latestTimestamp, ) = _aggregator.getRoundData(round);
        }
        return (round, uint256(latestPrice), latestTimestamp);
    }
```

## Impact

Potentially valuing already worthless tokens

## Code Snippet

[getLatestRoundData()](https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/1f9a5ed0ca8f6004bbb7b099ecbb8ae796557849/hubble-protocol/contracts/Oracle.sol#L106-L141)

## Tool used

Manual Audit

## Recommendation

Revert instead in the case where all of last hour data is negative

Duplicate of #99

**Comment by Bauchibred** [comment]
Escalate

This issue and #239 seem to have been wrongly duplicated to #99, I believe all three issues talk about different things
This issue for example was submitted after extensive discussion with the sponsors, and I would argue that valuing assets using their last positive value if all the returned price data for said asset from the last hour is negative isn't the best way to operate.

Additionally for #243 where as DOS issues are very trivial on Sherlock, I believe if a user can side step being liquidatable that means they can go further and game the system and leak value to a protocol, shouldn't this be valid, this was also submitted after extensive discussion with the sponsors.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue and #239 seem to have been wrongly duplicated to #99, I believe all three issues talk about different things
> This issue for example was submitted after extensive discussion with the sponsors, and I would argue that valuing assets using their last positive value if all the returned price data for said asset from the last hour is negative isn't the best way to operate.
> 
> Additionally for #243 where as DOS issues are very trivial on Sherlock, I believe if a user can side step being liquidatable that means they can go further and game the system and leak value to a protocol, shouldn't this be valid, this was also submitted after extensive discussion with the sponsors.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Please see sponsor response:

https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/99#issuecomment-1640394473

**Comment by IAm0x52** [comment]
Chainlink can't return a negative price due to to the min/max price limit

**Comment by hrishibhat** [comment]
@Bauchibred

**Comment by Bauchibred** [comment]
Appreciate all the comments by sponsors, lead judge & watson.

I'm convinced that the issue with the negative price is now no longer possible due to to chainlink's min/max breakers, this report was coined from the discussion with sponsors and was focused on hubble exchange's design choice of using the last positive price if all last hour's price is negative, imo since this is no longer possible, the check for negative price can now be completely removed.

Additionally #239, is not about negative price, but more of how the mitigation to hyh's issue tagged in the summary of the report was not completely mitigated against, would only be reasonable to note that I believe due to the min/max circuit breakers the window for this has been tightened, but I assume it's still possible for any feed with a min price limit lower than that, no?

Lastly, I would like any comment on #243.

**Comment by ctf-sec** [comment]
for issue #239 

yes the min / max circuit breaker should stop the price fall below 100

**Comment by ctf-sec** [comment]
for issue #243 

https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/1f9a5ed0ca8f6004bbb7b099ecbb8ae796557849/hubble-protocol/contracts/ClearingHouse.sol#L53

the number of amms is set in precompile and can be set by admin

in theory it is possible the loop running out of gas if there are so many amms set, but in reality, it is not possible, the admin should be able to adjust the precompiled amms parameter

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #99

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Bauchibred](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/244/#issuecomment-1645576144): accepted
